title: Lit Home
author:
  name: LitRitt
  email: dev@litritt.com
description: The home of all things Lit
url: "https://litritt.com"
github_url: "https://github.com/LitRitt/lit-home" # GitHub link for footer link. Comment out to remove link

show_excerpts: false # set to true to show excerpts on the homepage

lit-midnight:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: patreon, user_url: "https://www.patreon.com/litritt" }
    - { platform: discord, user_url: "https://discord.gg/qEtKFJt5dR" }
    - { platform: github, user_url: "https://github.com/litritt" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.md
  - ignited/index.md
  - guides.md

# Build settings
remote_theme: litritt/lit-midnight

exclude:
  - LICENSE.txt
  - README.md

whitelist:
  - jekyll-redirect-from